name: Temas para Live
description: Sugestão de temas para o canal.
title: "[Tema]: "
labels: ["sugestao-tema"]
assignees:
  - ocassiobotaro
body:
  - type: markdown
    attributes:
      value: |
        Desde já, obrigado pela sugestão!
  - type: input
    id: convidados
    attributes:
      label: Convidados
      description: Conhece alguém que poderia apresentar o tema?
      placeholder: ex. email@exemplo.com ou @nomedapessoa (Coloque os nomes separados por vírgula)
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: Mais detalhes
      description: Existe algum tópico específico que espera ser abordado?
      placeholder: "Adicione aqui um tópico específico ou uma breve descrição do que espera ser abordado sobre o tema"
    validations:
      required: false
  - type: dropdown
    id: version
    attributes:
      label: Quadro
      description: Qual o quadro do canal?
      options:
        - Botaro o Cássio no Youtube
        - Botaro o Cássio no Youtube - Mão na Massa
        - Meetup Python
        - Meetup Go
        - Outro
    validations:
      required: true
